### ISSUE TITLE
Numpy needed

### ISSUE THREAD

**Issue by cloudcloudskies** [bemxio/bad-apple-bootloader#4]
numpy needed in requirements, lazy to make pr

**Comment by bemxio** [comment]
`numpy` is `to-ascii`'s [dependency](https://github.com/Iapetus-11/To-ASCII/blob/master/pyproject.toml#L16) though, although i do remember when i once made a virtual environment for this project and it seems like To-ASCII's dependencies did not install at all and `pip` only took the cached package itself

**Comment by bemxio** [comment]
just to be extra safe i'll add it in real quick though, thanks!
